# QEMU aarch64 builder — the CI smoke target.
#
# This template uses HashiCorp's official `qemu` plugin (not the
# mkaczanowski/packer-builder-arm plugin used by rpi5.pkr.hcl). The
# Debian cloud image is a UEFI-bootable qcow2 already, so we don't need
# to mount-and-chroot the way `packer-builder-arm` does for raw Pi
# images. Boot the image, run cloud-init with an SSH key from
# packer/cloud-init/, run the Ansible role over SSH, then export the
# resulting qcow2.
#
# Output: build/qemu-aarch64-<profile>.qcow2

packer {
  required_version = ">= 1.10.0"
  required_plugins {
    qemu = {
      source  = "github.com/hashicorp/qemu"
      version = "~> 1.1"
    }
    ansible = {
      source  = "github.com/hashicorp/ansible"
      version = "~> 1.1"
    }
  }
}

variable "profile" {
  type        = string
  default     = "openclaw"
  description = "Profile id to bake. Must match a file in profiles/."
}

variable "channel" {
  type        = string
  default     = "dev"
  description = "Release channel for this build (dev | beta | stable)."
}

variable "tier" {
  type        = string
  default     = "standard"
  description = "Bundle tier (lean | standard | rich)."
}
variable "airgap" {
  type        = string
  default     = "0"
  description = "Air-gapped build (\"1\" or \"true\"); bakes LFM2 + locks egress. See docs/11-roadmap.md § M4.5."
}


variable "deputyos_staging_dir" {
  type        = string
  default     = "build/staging"
  description = "Host-side staging dir scripts/build.sh populates with deputyctl, profile manifest, and limits.json."
}

# Pinned Debian 12 (bookworm) generic arm64 cloud image, snapshot
# 20250316-2053. SHA512 published in the SHA512SUMS file alongside.
# Re-pin via scripts/build.sh by overriding base_image_url and
# base_image_checksum.
variable "base_image_url" {
  type        = string
  default     = "https://cloud.debian.org/images/cloud/bookworm/20250316-2053/debian-12-generic-arm64-20250316-2053.qcow2"
  description = "Pinned Debian 12 generic arm64 cloud image."
}

variable "base_image_checksum" {
  type        = string
  default     = "sha512:ddc9ffb68053ee02443eba9327381d7dbc2384bcf716565ec894d17d38930636b14b0c5aad867b519f8b018e2c29f9f59621c3e04cdbc51c6076aef5e85c4065"
  description = "SHA512 from cloud.debian.org/images/cloud/bookworm/20250316-2053/SHA512SUMS."
}

variable "ssh_username" {
  type        = string
  default     = "deputyos-build"
  description = "Throwaway user injected via cloud-init for the Packer SSH session."
}

source "qemu" "qemu-aarch64" {
  iso_url      = var.base_image_url
  iso_checksum = var.base_image_checksum

  # We're starting from a qcow2, not an ISO — `disk_image=true` tells
  # the plugin to use it as the boot disk directly.
  disk_image       = true
  disk_size        = "8G"
  format           = "qcow2"
  output_directory = "build/packer-qemu-aarch64"
  vm_name          = "qemu-aarch64-${var.profile}.qcow2"

  # aarch64 cross-arch on x86_64 host. Use TCG (no nested KVM needed).
  qemu_binary    = "qemu-system-aarch64"
  machine_type   = "virt"
  cpus           = 2
  memory         = 4096
  accelerator    = "tcg"
  use_default_display = false
  headless       = true

  # UEFI firmware — Debian arm64 cloud images are EFI-only.
  firmware = "/usr/share/AAVMF/AAVMF_CODE.fd"

  # NoCloud seed ISO with cloud-init user-data. Generated by
  # scripts/build.sh before invoking packer.
  cd_files = ["${var.deputyos_staging_dir}/cloud-init/user-data",
              "${var.deputyos_staging_dir}/cloud-init/meta-data"]
  cd_label = "cidata"

  ssh_username     = var.ssh_username
  ssh_private_key_file = "${var.deputyos_staging_dir}/ssh-key"
  ssh_timeout      = "10m"
  ssh_port         = 22

  # Cloud images on aarch64 don't expose a graphical console; route
  # serial to packer's log so first-boot failures are debuggable.
  qemuargs = [
    ["-cpu", "cortex-a72"],
    ["-serial", "stdio"],
  ]

  shutdown_command = "sudo shutdown -P now"
}

build {
  name    = "qemu-aarch64"
  sources = ["source.qemu.qemu-aarch64"]

  provisioner "ansible" {
    playbook_file = "packer/playbook.yml"
    user          = var.ssh_username
    use_proxy     = false
    extra_arguments = [
      "--extra-vars",
      join(" ", [
        "deputyos_hw=qemu-aarch64",
        "deputyos_profile=${var.profile}",
        "deputyos_channel=${var.channel}",
        "deputyos_tier=${var.tier}",
        "deputyos_airgap=${var.airgap}",
        "deputyos_staging_dir=${var.deputyos_staging_dir}",
        "deputyctl_path=${var.deputyos_staging_dir}/deputyctl",
        "profile_staging_path=${var.deputyos_staging_dir}/profiles",
        "limits_staging_path=${var.deputyos_staging_dir}/limits.json",
      ]),
    ]
  }

  post-processor "shell-local" {
    inline = [
      "mkdir -p build",
      "cp build/packer-qemu-aarch64/qemu-aarch64-${var.profile}.qcow2 build/qemu-aarch64-${var.profile}.qcow2",
    ]
  }
}
