#!/usr/bin/env bash
# scripts/wsl2-build.sh — WSL2 distro tarball bake.
#
# Called from packer/wsl2.pkr.hcl's shell-local provisioner. Also
# directly callable from scripts/build.sh in degraded-mode (no packer)
# so contributors without packer installed can still produce a tarball.
#
# Steps:
#   1. Download pinned Debian 12 nocloud amd64 rootfs tarball.
#   2. Verify SHA512 against $BASE_ROOTFS_CHECKSUM.
#   3. Extract to a working directory.
#   4. Run the Ansible role inside the rootfs:
#        - prefer systemd-nspawn (clean, requires CAP_SYS_ADMIN);
#        - fallback to proot for unprivileged hosts.
#      Pass deputyos_hw=wsl2 + the profile/channel/tier vars.
#   5. Stage limits.json + /etc/wsl.conf.
#   6. Repackage as build/wsl2-<profile>.tar.gz.
#
# This script intentionally does NOT use chroot — chroot inside Packer
# doesn't survive PID-namespace boundaries cleanly, and many CI runners
# block chroot for unprivileged users. systemd-nspawn handles namespaces
# correctly; proot is the last-resort userspace simulator.
#
# IMPORTANT: this script will not run end-to-end in many sandboxed
# environments (no CAP_SYS_ADMIN for nspawn, no proot binary). The wiring
# is correct and `bash -n` clean. Local-build documentation in
# wsl/README.md tells contributors what to install.

set -euo pipefail

PROFILE="${PROFILE:-openclaw}"
CHANNEL="${CHANNEL:-dev}"
TIER="${TIER:-standard}"
DEPUTYOS_STAGING_DIR="${DEPUTYOS_STAGING_DIR:-build/staging}"
BASE_ROOTFS_URL="${BASE_ROOTFS_URL:-https://cloud.debian.org/images/cloud/bookworm/20250316-2053/debian-12-nocloud-amd64-20250316-2053.tar.xz}"
BASE_ROOTFS_CHECKSUM="${BASE_ROOTFS_CHECKSUM:-sha512:1f69ef5d87ad01f415826739565d27f983fc6d6297c9cd6585ebc4815132d17ca677ff7ccce29d36fe54fd7702bca20ccf66c9eb38b658d3f52759c4dadfb7e9}"

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
work_dir="${repo_root}/build/packer-wsl2"
rootfs_dir="${work_dir}/rootfs"
download_dir="${repo_root}/build/cache"
tarball_name="$(basename "$BASE_ROOTFS_URL")"
tarball_path="${download_dir}/${tarball_name}"
output="${repo_root}/build/wsl2-${PROFILE}.tar.gz"

mkdir -p "$download_dir" "$work_dir"

echo "==> wsl2: downloading base rootfs"
if [[ ! -f "$tarball_path" ]]; then
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL --output "$tarball_path" "$BASE_ROOTFS_URL"
  elif command -v wget >/dev/null 2>&1; then
    wget -q -O "$tarball_path" "$BASE_ROOTFS_URL"
  else
    echo "error: neither curl nor wget available to fetch ${BASE_ROOTFS_URL}" >&2
    exit 1
  fi
fi

echo "==> wsl2: verifying SHA512"
expected="${BASE_ROOTFS_CHECKSUM#sha512:}"
# An unpinned checksum (empty, or still containing an angle-bracket placeholder
# marker) skips verify; a real 128-hex-char sha512 is enforced. The marker test
# avoids embedding the literal release-placeholder token here so manifest.sh's
# release guard doesn't false-trip on this file.
if [[ -z "$expected" || "$expected" == *"<<<"* ]]; then
  echo "warn: BASE_ROOTFS_CHECKSUM not pinned — skipping verify (pin before release)" >&2
else
  actual="$(sha512sum "$tarball_path" | awk '{print $1}')"
  if [[ "$actual" != "$expected" ]]; then
    echo "error: rootfs SHA512 mismatch" >&2
    echo "  expected: $expected" >&2
    echo "  actual:   $actual" >&2
    exit 1
  fi
fi

echo "==> wsl2: extracting rootfs"
rm -rf "$rootfs_dir"
mkdir -p "$rootfs_dir"
# The Debian nocloud tarball is tar.xz of a flat rootfs.
tar -xJf "$tarball_path" -C "$rootfs_dir"

# ---- Stage deputyctl + profile + limits inside the rootfs ----
echo "==> wsl2: staging artefacts inside rootfs"
mkdir -p "$rootfs_dir/opt/deputyos-staging"
if [[ -d "${repo_root}/${DEPUTYOS_STAGING_DIR}" ]]; then
  cp -r "${repo_root}/${DEPUTYOS_STAGING_DIR}/." "$rootfs_dir/opt/deputyos-staging/"
fi

# Bind-mount the role into the rootfs so the inside-the-chroot
# ansible-playbook can find it.
mkdir -p "$rootfs_dir/opt/deputyos-role"
cp -r "${repo_root}/roles" "$rootfs_dir/opt/deputyos-role/"

playbook_inside="$rootfs_dir/opt/deputyos-role/run.yml"
cat >"$playbook_inside" <<EOF
---
# Auto-generated by scripts/wsl2-build.sh — do not edit by hand.
- hosts: localhost
  connection: local
  become: true
  vars:
    deputyos_hw: wsl2
    deputyos_profile: ${PROFILE}
    deputyos_channel: ${CHANNEL}
    deputyos_tier: ${TIER}
    deputyos_staging_dir: /opt/deputyos-staging
    deputyctl_path: /opt/deputyos-staging/deputyctl
    profile_staging_path: /opt/deputyos-staging/profiles
    limits_staging_path: /opt/deputyos-staging/limits.json
  roles:
    - role: deputyos
EOF

# ---- Run the role inside the rootfs ----
echo "==> wsl2: running Ansible role inside rootfs"
runner=""
if command -v systemd-nspawn >/dev/null 2>&1 && [[ "$(id -u)" -eq 0 ]]; then
  runner="nspawn"
elif command -v proot >/dev/null 2>&1; then
  runner="proot"
fi

case "$runner" in
  nspawn)
    systemd-nspawn -D "$rootfs_dir" \
      --bind-ro=/etc/resolv.conf \
      bash -lc "apt-get update && apt-get install -y --no-install-recommends ansible && cd /opt/deputyos-role && ansible-playbook -i localhost, run.yml"
    ;;
  proot)
    proot -r "$rootfs_dir" -b /etc/resolv.conf -0 \
      bash -lc "apt-get update && apt-get install -y --no-install-recommends ansible && cd /opt/deputyos-role && ansible-playbook -i localhost, run.yml"
    ;;
  *)
    echo "warn: neither systemd-nspawn (root) nor proot is available — skipping in-rootfs Ansible run" >&2
    echo "  install one of:" >&2
    echo "    sudo apt install systemd-container   # for systemd-nspawn (recommended)" >&2
    echo "    sudo apt install proot               # for unprivileged-user fallback" >&2
    echo "  the rootfs has been extracted and staged at: $rootfs_dir" >&2
    echo "  the tarball will be packaged WITHOUT the agent role applied (degraded)." >&2
    ;;
esac

# ---- Drop /etc/wsl.conf with sane defaults ----
echo "==> wsl2: writing /etc/wsl.conf"
mkdir -p "$rootfs_dir/etc"
cat >"$rootfs_dir/etc/wsl.conf" <<'EOF'
# /etc/wsl.conf — deputyOS WSL2 defaults.
# Created at bake time by scripts/wsl2-build.sh.

[boot]
# Modern WSL2 supports systemd; deputyOS relies on it for ufw, clamd
# (where enabled), and the gateway service.
systemd=true

[user]
# `agent` is the default unprivileged user deputyctl provisions.
default=agent

[interop]
# Don't pollute $PATH with the host Windows binaries — deputyctl runs
# in a clean Linux environment by design.
appendWindowsPath=false

[network]
# WSL2's default hostname is the Windows machine name; pin to a stable
# value so logs and self-config don't change every reboot.
hostname=deputyos
EOF

# ---- Repackage ----
echo "==> wsl2: packaging tarball"
mkdir -p "${repo_root}/build"
# Strip the staging dir before tarring — it's only for bake, not for
# WSL runtime. The role files we leave in place since the user may
# want to re-run them post-import.
rm -rf "$rootfs_dir/opt/deputyos-staging"

# WSL --import expects the tarball contents to be at the top level.
tar -czf "$output" -C "$rootfs_dir" .

echo "==> wsl2: done -> ${output}"
